#!/bin/sh
set -o errexit
set -o pipefail
set -o nounset
set -x

BUILDER_MODE="${BUILDER_MODE:-false}"

# Starting builder mode if there is new content to build, or no current build could be found
if [ "${BUILDER_MODE}" = "true" ] && { [ "$(cat ./.next/current/BUILD_ID)" != "$NEXT_BUILD_ID" ] || [ ! -f ./.next/current/D0NE ]; } then
  /usr/local/bin/next-build.sh
fi

# run app from latest dir
# BUILD_DIR="./.next/current" /usr/local/bin/npm run start
/usr/local/bin/npm run dev
